### ISSUE TITLE
Does this work on windows?

### ISSUE THREAD

**Issue by akokoduru** [Kakamotobi/bleeper#1]
Hi, this is so nice! 
I was wondering if it also works on Asus. thanks

**Comment by Kakamotobi** [comment]
Thanks, lookalee from San Diego! Assuming your OS is Windows, you can download and install the "Bleeper-Windows.msi" install file [here](https://github.com/Kakamotobi/bleeper/releases/tag/v1.0.0).

**Comment by akokoduru** [comment]
Thanks, kaka!
