### ISSUE TITLE
Support for macOS Monterey (M1)? 

### ISSUE THREAD

**Issue by akokoduru** [Kakamotobi/bleeper#2]
Does this support macOS Monterey (M1)?  I downloaded the 'Bleeper-MacOS-AppleSilicon.dmg' file, but when i click it, nothing happens.

**Comment by Kakamotobi** [comment]
Yes it should work. Could you try again with the install file that I've reuploaded? 
[Bleeper-MacOS-AppleSilicon.dmg](https://github.com/Kakamotobi/bleeper/releases/download/v1.0.0/Bleeper-MacOS-AppleSilicon.dmg)

**Comment by akokoduru** [comment]
> Yes it should work. Could you try again with the install file that I've reuploaded? [Bleeper-MacOS-AppleSilicon.dmg](https://github.com/Kakamotobi/bleeper/releases/download/v1.0.0/Bleeper-MacOS-AppleSilicon.dmg)

Thanks, it worked.

But I got this error when I opened Bleeper

![image](https://github.com/Kakamotobi/bleeper/assets/36493381/40c99e47-9cb6-485a-80d8-73c3bfb5ad1a)

Can you help?

**Comment by akokoduru** [comment]
bump

**Comment by Kakamotobi** [comment]
Oops. Forgot I have to sign it for MacOS. I don't plan on doing so yet since it's a bit pricy.
